Docs for Deleting Repo Host STS Following Upgrade from 5.0.0-5.0.2
CrunchyData/postgres-operator pull request #2859
Opened 2021-11-17 20:22 UTC by andrewlecuyer

Adds upgrade documentation that instructs users to delete the dedicated repository StatefulSet following an upgrade from `v5.0.0-5.0.2` if a certain error is seen in the PGO logs that prevents reconciliation.

**Checklist:**

 
 - [x] Have you added an explanation of what your changes do and why you'd like them to be included?
 - [x] Have you updated or added documentation for the change, as applicable?
 - [ ] Have you tested your changes on all related environments with successful results, as applicable?
   - [ ] Have you added automated tests?

**Type of Changes:**

 
 - [ ] New feature
 - [ ] Bug fix
 - [x] Documentation
 - [ ] Testing enhancement
 - [ ] Other

**What is the current behavior (link to any open issues here)?**
N/A

[sc-13164]

**What is the new behavior (if this is a feature change)?**
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

N/A

**Other Information**:
N/A

2021-11-17 20:37 UTC, benjaminjb approved these changes
Seems reasonable. (I don't think the two uses of "proceed with" are too many, but I did want to  point it out in case someone else feels differently.)

2021-11-17 21:33 UTC, jkatz requested changes

2021-11-17 21:33 UTC, jkatz commented on docs/content/installation/upgrade.md
> +## Upgrading from PGO 5.0.0-5.0.2
```suggestion
## Upgrading from PGO v5.0.2 and below
```

2021-11-17 21:33 UTC, jkatz commented on docs/content/installation/upgrade.md
> +error (as shown in the PGO logs) following an upgrade from PGO versions 5.0.0-5.0.2:
```suggestion
error (as shown in the PGO logs) following an upgrade from PGO versions v5.0.0 through v5.0.2:
```

2021-11-17 21:33 UTC, jkatz commented on docs/content/installation/upgrade.md
> +As a result of changes to pgBackRest dedicated repository host deployments in PGO 5.0.3
```suggestion
As a result of changes to pgBackRest dedicated repository host deployments in PGO v5.0.3
```

2021-11-17 21:33 UTC, jkatz commented on docs/content/installation/upgrade.md
> +(please see the [PGO 5.0.3 release notes]({{< relref "../releases/5.0.3.md" >}}) for more details),
```suggestion
(please see the [PGO v5.0.3 release notes]({{< relref "../releases/5.0.3.md" >}}) for more details),
```

2021-11-17 21:33 UTC, jkatz commented on docs/content/installation/upgrade.md
> +[PGO 5.0.3 release notes]({{< relref "../releases/5.0.3.md" >}}).
```suggestion
[PGO v5.0.3 release notes]({{< relref "../releases/5.0.3.md" >}}).
```

2021-11-17 22:36 UTC, andrewlecuyer commented
@jkatz all feedback has been addressed.

2021-11-18 17:39 UTC, jkatz approved these changes

2021-11-18 17:39 UTC, merged