Upgrade conditions
CrunchyData/postgres-operator pull request #3861
Opened 2024-02-27 21:46 UTC by ValClarkson

**Checklist:**

 
 - [ ] Have you added an explanation of what your changes do and why you'd like them to be included?
 - [ ] Have you updated or added documentation for the change, as applicable?
 - [ ] Have you tested your changes on all related environments with successful results, as applicable?
   - [ ] Have you added automated tests?

**Type of Changes:**

 
 - [x ] New feature
 - [ ] Bug fix
 - [ ] Documentation
 - [ ] Testing enhancement
 - [ ] Other

**What is the current behavior (link to any open issues here)?**

**What is the new behavior (if this is a feature change)?**
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

Added conditions for upgrading the cluster

**Other Information**:

2024-02-28 01:02 UTC, dsessler7 requested changes
So I think we want something similar to what Ben did on lines 259-274 in `crunchybridgecluster_controller.go` where we check to see if an error condition is in place. If there is an error condition, we check the observed generation. If the observed generation hasn't changed, meaning the customer hasn't changed the spec, then we want to return early.

2024-02-28 23:37 UTC, ValClarkson commented on internal/bridge/crunchybridgecluster/crunchybridgecluster_controller.go
> +		})
Updated

2024-02-28 23:38 UTC, ValClarkson commented on internal/bridge/crunchybridgecluster/crunchybridgecluster_controller.go
> +					operation.Flavor, operation.State, crunchybridgecluster.Name),
removed everywhere I had it in the conditions

2024-02-28 23:39 UTC, ValClarkson commented on internal/bridge/crunchybridgecluster/crunchybridgecluster_controller.go
> +					"for cluster %v", crunchybridgecluster.Name),
updated

2024-02-28 23:39 UTC, ValClarkson commented on internal/bridge/crunchybridgecluster/crunchybridgecluster_controller.go
> +					"for cluster %v", crunchybridgecluster.Name),
updated

2024-02-28 23:39 UTC, ValClarkson commented on internal/bridge/crunchybridgecluster/crunchybridgecluster_controller.go
> +			"HA upgrade in progress to %v on the Crunchy Bridge Cluster %v", action, crunchybridgecluster.Name),
fixed

2024-02-28 23:39 UTC, ValClarkson commented on internal/bridge/crunchybridgecluster/crunchybridgecluster_controller.go
> +	}
updated

2024-02-28 23:40 UTC, ValClarkson commented on internal/bridge/crunchybridgecluster/crunchybridgecluster_controller.go
> +		for _, operation := range clusterUpgradeDetails.Operations {
updated

2024-02-29 01:33 UTC, dsessler7 approved these changes
Couple nitpicks, but looks good otherwise.

2024-02-29 01:33 UTC, dsessler7 commented on internal/bridge/crunchybridgecluster/crunchybridgecluster_controller.go
> +	invalidUpgrade := meta.FindStatusCondition(crunchybridgecluster.Status.Conditions,
:pick: A comment above this block of code explaining what it is doing would be nice.

2024-02-29 01:33 UTC, dsessler7 commented on internal/bridge/crunchybridgecluster/crunchybridgecluster_controller.go
> +				"Error performing an HA upgrade %v:", err),
```suggestion
				"Error performing an HA upgrade: %v", err),
```

2024-02-29 19:25 UTC, merged